### ISSUE TITLE
No info about Neovim support

### ISSUE THREAD

**Issue by vbauerster** [cosminadrianpopescu/vim-sql-workbench#21]
There is no information about neovim support neither in readme nor in docs.
Is neovim supported?
If not better to mention about it at least in the readme.
If yes, so at what degree? Will this plugin benefit of neovim async support?

**Comment by cosminadrianpopescu** [comment]
Yes, you are right. Neovim support is though in the changelog of 6.1. Neovim is fully supported. The only thing which does not work in neovim is the ability to cancel an ongoing query, which is why this functionality is not mentioned anywhere at the moment. 

But the async support of vim > 7.4 is actually better implemented than the async support of neovim (in terms of API) because of partial functions and the way a job could be launch.
