### ISSUE TITLE
Intellisense Autocomplete not working

### ISSUE THREAD

**Issue by dvkchaitanya** [cosminadrianpopescu/vim-sql-workbench#22]
Firstly I want to thank you for implementing sql workbench in vim. I am able to set up this plugin successfully. Only problem I am facing is that, when I am pressing Ctrl+X, Ctrl+U, intellisense is not working. I am getting the following error message: "E764 : option 'completefunc' is not set".  Can you please let me know what could went wrong.

**Comment by cosminadrianpopescu** [comment]
Sorry for the late reply. I either didn't got an e-mail from `github` or I didn't noticed it. So, in order to get the autocomplete working, you have to set it first:

* `:SWSqlAutocomplete` - this command can take some time (depending on your database size). When this is finished, you can do `ctrl-x ctrl-u`.
* `:SWSqlAutocompletePersist <id>` - once the autocomplete cache is created, you can persist it, so next time you can load it automatically without having to wait for it to be created
* once you persisted the autocomplete cache, next time you do `:SWSqlAutocompleteLoad <id>`

If you then modify a table, you can load into cache just the modified table (see the documentation, section intellisense on how to do that) and then you can persist again the cache with the same identifiant

**Comment by cosminadrianpopescu** [comment]
Starting with version 7.0, to have intellisense, you have to set one of the options `report` to true or `use-report` in the profile extended properties (in GUI). See the `Schema report` section in the documentation.

**Comment by Alieff** [comment]
It is a great plugin, I really like it. 
So far so good, except for the intellisense feature.

I have set the extended property `report` to true.
When I checked on the cache folder (`g:sw_cache`) the report seems exists. 
There are several files in that folder, two of them:
- `<MyDB>` (containing xml about my database)
- `<MyDB>.vim` (containing xml, with many line like `let b:schema_report....`)

But when I tried to trigger the autocompletion (<c-x><c-u>) nothing happened.
I tried <c-x><c-o>, an error showed up, `E745: Using a List as a Number`

Is there something that I missed?
