### ISSUE TITLE
could you please post your vimrc?

### ISSUE THREAD

**Issue by absurdist** [cosminadrianpopescu/vim-sql-workbench#24]
hello,

thank you i am really enjoying using your project.
it has taken me a while to figure out the configuration, and a vimrc would be very helpful.

thank you

Mat

**Comment by cosminadrianpopescu** [comment]
My `vimrc` you can find it [here](https://github.com/cosminadrianpopescu/dotfiles).

It's quite a big `vimrc`, but the essential parts in it are these:

```
let g:airline_extensions = ['ctrlp', 'undotree', 'netrw', 'quickfix', 'sw', 'tabline', 'obsession']
let g:ctrlp_extensions = ['funky', 'java_types', 'jumps', 'sw_profiles']
let g:sw_exe = '/home/lixa/programs/sql-workbench-122.3/sqlwbconsole.sh'
let g:sw_config_dir = '/home/lixa/.sqlworkbench/'
let g:sw_log_to_file = 1
```

When you said that it took you a while to figure out the config, what are you referring to? Because, to get started, it should be just the `g:sw_exe` and `g:sw_config_dir` variables to set and you are ready to go. And those two variables are in the tutorial (first paragraph in documentation). 

I am trying to make this as user friendly as possible, so could you please share what problems you had, to make the docs more readable?

Thank you for using it,
Cosmin Popescu.

**Comment by absurdist** [comment]
thanks cosmin,
yes to get started was quick.

I'm running vim at work, on windows in git-bash and haven't got ctrlp integration working - sw_profiles doesn't find any profiles, and was wondering if I was misunderstanding the documentation

thanks for the vimrc

regards mat

**Comment by cosminadrianpopescu** [comment]
Let me know if everything is ok to close this issue. However, on windows you also have to set `g:sw_tmp` variable, which by default is `/tmp`. But when you say the `sw_profiles` is not working, what problems are you having? Normally, if you set `g:sw_config_dir` the `sw_profiles` should work without issue. What `sw_profiles` is doing is parging the `WbProfiles.xml` file which should be in the `g:sw_config_dir` folder. 

Or I missunderstood your problem?

**Comment by absurdist** [comment]
thanks cosmin, they are all configured (sw_profiles , sw_config_dir) WbProfiles.xml is in the directory, and contains my profile, but ctrlP, in sql workbench profiles mode doesn't find the profile and displays ==NO ENTRIES==.

**Comment by cosminadrianpopescu** [comment]
Are you by any chance running vim under a cygwin?

**Comment by absurdist** [comment]
hello cosmin,

i'm running under git-bash on windows,

it maybe that that is built on cygwin under the covers, i'll look into it.


thanks

mat

**Comment by cosminadrianpopescu** [comment]
i think the issue is with the paths. you have to put in the linux paths, if you are under cygwin. for example, `/cygdrive/c/Users/...`. the problem is that basically the `WbPrifiles.xml` file is not found, i think.

**Comment by absurdist** [comment]
thank you for taking the time to assist me cosmin,


I started out with a unix path, also tried a windows path.

do you have any suggestions on how to debug the ctlp plugin?

regards

mat

**Comment by cosminadrianpopescu** [comment]
The `ctrlp` extension checks the `WbProfiles.xml` file, is parsing it and extracts the necessary info from there.

Could you please go to the command mode in vim, and execute `sw#profiles#get()`

```
:echo sw#profiles#get()
```

Please check if anyprofile is found.

Then, could you please post the following vim variables: `g:sw_tmp`, `:g:sw_config_dir`. `g:sw_autocomplete_cache_dir`? 

I think that it actually could be that the `g:sw_autocomplete_cache_dir` variable is not set. I will probably need to modify the documentation, but I want to be sure first. 

Thank you, 
Cosmin Popescu.

**Comment by cosminadrianpopescu** [comment]
Could you please install the latest version (`7.1.1`). If the `g:sw_cache` variable is not set, you should have an error message when starting `vim`. The default value is `~/.cache/sw`. You can either create the folder, or you can set the variable. Once this is done, you should restart vim and the `CtrlP` integration should work. 

Please let me know how it goes.

Thank you, 
Cosmin Popescu.

**Comment by absurdist** [comment]
thank you cosmin,

not working unfortunately.
I might try and see if I can get it to run under windows directly




all of these echo like this:

sw_config_dir /c/Users/mjd/.sqlworkbench/
sw_tmp /c/temp
sw_autocomplete_cache_dir /d/sw-cache/sw
 

the config directory is correct:

/c/Users/mjd/.sqlworkbench
$ ls WbProfiles.xml
WbProfiles.xml


but doesn't seem to work:

There was a problem fetching the profiles for Sql Workbench (maybe the g:sw_cache) variable is not set?
 
sw#profiles#get()
 
{}
 

thanks for all your help

Mat

**Comment by cosminadrianpopescu** [comment]
First of all, even if you are in a cygwin environment, the window path should work. So: 

1. change the paths like this:

* `g:sw_config_dir` to c:/Users/mjd/.sqlworkbench/
* `g:sw_tmp` to c:/temp
* `g:sw_cache` to d:/sw-cache/sw (please note that this replaces the `g:sw_autocomplete_cache_dir` starting with the last version)

Check that the d:/sw-cache/sw folder exists and that you have read/write persmissions to it. 

Normally after this, everything should be fine.

Please let me know if you still have issues. 

As a bonus, if you also want intellisense autocomplete, open the GUI of sql workbench, go to your profile and click on `Extended properties` and create a new one which is called `report` with the value `true`. After this, close the GUI of `SQL Workbench`, restart your `vim` and reconnect with the profile. 

If you do `<C-x><C-u>`, after a `select * from `, you should see a list of all the tables and views in the database. If you select a table and you do again `<C-x><C-u> after for example a `where` condition, you will see the list of fields in that table.

Let me know how it works now.

Cosmin Popescu.

**Comment by absurdist** [comment]
thanks cosmin,

I'll also look for where you display that error message, and add some more messages
 to try and debug out where it is failing

regards

mat

**Comment by cosminadrianpopescu** [comment]
But is it still failing? If you change the paths and install the latest version it should work. If it is still failing, then sure, add debug messages and let's try to see what's happening.

**Comment by absurdist** [comment]
hi cosmin, could i ask some questions about what the code should be doing ?
thank you mat

from /plugin/sw.vim

```
if !exists('g:cache')
    let g:sw_cache = $HOME . '/.cache/sw'
endif
```

should that be :

`if !exists('g:sw_cache')`

**Comment by absurdist** [comment]
Hi cosmin,

I've got an idea, wbabout is returning the path to the connection profiles as a windows path.
I've found earlier that vim under git bash isn't happy with windows paths, so i'll hardcode the path as a unix path to see if that's the problem,

regards

mat

**Comment by cosminadrianpopescu** [comment]
Yes, the exists('g:cache') is a bug. it should be exists('g:sw_cache'). I will try to also install a git bash and see what happens. 

I am using this plugin on a daily basis under `cygwin` and I've assumed that it will work also for a `git bash`. However, what you could try is only reverse the slashes in the paths (instead of `c:\Users`, have `c:/Users` and see if this helps. Anyway, I will install a `git bash` and see what happens.

**Comment by cosminadrianpopescu** [comment]
So, I reproduced the bug. I will create tonight a fix for it. Meanwhile, anyway, because you are running under `cygwin`, you also have to set the variable `g:sw_plugin_path` which should point to the installation of `vim-sql-workbench` plugin. This is needed only in cygwin environments (since `git-bash` is a `cygwin` environment, it needs the same variable set. 

So, tonight I will create a patch with the doc's modification and with the fix for the `g:cache` in the `plugin/sw.vim`. Meanwhile, if you are in a hurry you can fix the `plugin/sw.vim` file and either create a pull request, either wait for the release. After fixing the file, just add also the `g:sw_plugin_path` variable in your `vimrc` and you should rock and roll. 

Thank you for testing it and using it, 
Cosmin Popescu.

**Comment by cosminadrianpopescu** [comment]
Just added a new version. Install this version, set the `g:sw_plugin_path` variable and let me know how it goes. Please note that this version also fixed the problem with the `g:sw_cache` variable.

**Comment by absurdist** [comment]
wow Cosmin,

this is an amazing amount of effort you've gone to.

thank you for all your help.

I'm not at work at the moment, I'll install in a few hours and get back to you tonight


regards

Mat

**Comment by absurdist** [comment]
wow Cosmin,

this is an amazing amount of effort you've gone to.

thank you for all your help.

I'm not at work at the moment, I'll install in a few hours and get back to you tonight


regards

Mat

**Comment by absurdist** [comment]
Thanks cosmin,

it's working.

Thank you for all the effort you put into assisting me.

best regards

Mat
