### ISSUE TITLE
Execution of a large scripts is not possible

### ISSUE THREAD

**Issue by borisbrodski** [cosminadrianpopescu/vim-sql-workbench#30]
vim-sql-workbench is not able to execute a large files with SQL and PL/SQL scripts. I do following

- Open a file with the file in VIM
- Connect the buffer to the DB using `:CtrlP`
- Select all `ggVG`
- Execute `<leader>Ctrl+2` (this is the only shortcut, that executes current or selected statements for me)

It hangs for a very long time after printing (in my case)

    7814 lines yanked
    Processing a command. Please wait...

In this case I have to execute a 7814 lines long collection of 193 PL/SQL snippets like

    BEGIN
        ...
    END
    /

What I expect:

- Execution of SQL-snippets starts without a long delay
- It is possible to abort the execution at any time
- After execution of each block the result is added to the output buffer titled with the progress indicator, like (50/193). Here is an example of the SQL-Workbench GUI output for a PL-SQL-snippet:

        PL/SQL block executed

        Execution time: 0.15s
        Statement 192 of 193 finished

    even better for VIM would be something like this

        =PL/SQL block executed in 0.15s (Statement 192 of 193)
        possible output here (DBMS or result of a select)

    or at least

        = Statement executed (Statement 192 of 193)
        PL/SQL block executed in 0.15s

The SQL-Developer has no problems executing my large file. Also SQL-Workbench GUI executes the it within just 35 seconds (by selecting all with `Ctrl+A` and executing with `Ctrl+E` within the SQL-Workbench GUI (not in VIM)).

**Comment by cosminadrianpopescu** [comment]
Yes, this is a little bit tricky. Normally, as a work-around you can executed with wbinclude (see http://www.sql-workbench.net/manual/wb-commands.html#command-wbinclude). 

I don't know if this can even be done. It would mean that the plugin should split the visual selection in statements and then sending them one by one to the server. But as you say, as it is enclosed with a 
```
BEGIN
END
/
```

it would serve no point. 

The problem here is that `SQL Workbench/J` in console mode, would not send any information about the execution. So this cannot be implemented. 

What I recommend, as a work-around for the moment, try and use `wbinclude`. What I will try to fix here is the speed. But for this, I would need to add another command, like `SWSqlExecuteAsBlock`. because the long delay and blocking of VIM is because of the plugin will try and parse the 7000+ lines using regular expressions. 

By doing `SWSqlExecuteAsBlock`, I would assume that this problem will go away. But still, you will not have any output. After 35 seconds you will see only the final result.

**Comment by borisbrodski** [comment]
Couple more notes:

- VIM hangs completely. It has to be killed.
- Just tested a smaller file (304 lines) and it worked

The output:

    =SQL 18
    PL/SQL block executed
    Execution time: 0.18s

    =SQL 17
    PL/SQL block executed
    Execution time: 0.14s

    ...

is also good. (but may be improved a little bit :) )

Also:
- Vim: 8.0
- vim-sql-workbench: 8.0.1

**Comment by cosminadrianpopescu** [comment]
See my comment above

**Comment by cosminadrianpopescu** [comment]
Of course, the `wbinclude` should be executed from another script, pointing to the 7000+ lines script.

**Comment by borisbrodski** [comment]
In my case all the statements are separated my a line containing "/". So no big parsing is necessary here. I don't know, if this is a such common practice. I think, SQL-developer would also execute a script without "/"-separation lines.

I will try to use `wbinclude`. Thank you!

**Comment by borisbrodski** [comment]
`wbinclude` works! It produces less useful result, but it's ok.

What you could also probably do is to define some threshold (count of lines/bytes) for a SQL-block, exceeding which you would automatically create a temporary file, copy the SQL-Block into it and run it using `wbinclude`.

Hanging VIM with a lot of open buffers and potentially unsaved data is not a nice thing to get (hitting accidentally a wrong hot key)

**Comment by cosminadrianpopescu** [comment]
>What you could also probably do is to define some threshold (count of lines/bytes) for a SQL-block, exceeding which you would automatically create a temporary file, copy the SQL-Block into it and run it using wbinclude.

I will try to implement this in the next version

**Comment by cosminadrianpopescu** [comment]
I've created #34 

Si I am closing this one. Please let me know (and eventually create another ticket) if I've forgot something.
