### ISSUE TITLE
SWInclude: Wrong error message it in unconnected buffer

### ISSUE THREAD

**Issue by borisbrodski** [cosminadrianpopescu/vim-sql-workbench#35]
https://github.com/cosminadrianpopescu/vim-sql-workbench/blob/acc41ef44fa7028d608c6055b79696da1fc0b03e/autoload/sw/sqlwindow.vim#L120

Inside an unconnected buffer the `b:delimiter` is not defined.

**Comment by cosminadrianpopescu** [comment]
Yes, but this is normal. Because if you do `SWInclude`, how will the plugin know against which profile to execute the query? So this is normal behavior. The only fix I've implemented here is to give a proper error message when the buffer is not connected.

However, there is an issue with an unnamed buffer when doing `SWInclude`, so I will try to fix this.

**Comment by cosminadrianpopescu** [comment]
For an unnamed buffer, since there is no name, there is no way to do a `wbinclude` so now I've put in place a proper error message.
