### ISSUE TITLE
How to edit cell?

### ISSUE THREAD

**Issue by lluke777** [cosminadrianpopescu/vim-sql-workbench#40]
Hi. Plugin looks promessing :)
I am not familiar very welll with plugin, but got one question. Is there a mode where you have a table view and you can interactively edit cell by cell and putting new values using some keyboard shortcuts?

Thank you for your answer.

**Comment by cosminadrianpopescu** [comment]
Unfortunately, no. This plugin is just a wrapper for `SQL Workbench/J`. It does nothing that the `SQL Workbench` doesn't do (console mode). And since `SQL Workbench/J` in console mode is readonly, this feature will never be implemented. 

As a work-around I can suggest you to export the table as Excel, modify the data and import it back. But please be aware that I've never tested this workflow, so I cannot guarantee any results.
